# Generated by Django 6.0.1 on 2026-03-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Extensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=100)),
                ('oitava', models.IntegerField()),
                ('simples', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('compositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='obras.compositor')),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2)),
                ('extensao_fim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgaos_fim', to='obras.extensao')),
                ('extensao_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgaos_inicio', to='obras.extensao')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgaos', to='obras.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Registacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mao_esquerda', models.CharField(max_length=50)),
                ('mao_direita', models.CharField(max_length=50)),
                ('geral', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registacoes', to='obras.obra')),
            ],
        ),
    ]
