# Generated by Django 6.0.1 on 2026-03-08 13:27

import django.db.models.deletion
from django.db import migrations, models


def convert_genero_text_to_fk(apps, schema_editor):
    Obra = apps.get_model('obras', 'Obra')
    Genero = apps.get_model('obras', 'Genero')

    sem_genero, _ = Genero.objects.get_or_create(nome='Sem genero')

    for obra in Obra.objects.all().only('id', 'genero'):
        valor = (obra.genero or '').strip()
        if not valor:
            obra.genero = str(sem_genero.id)
        else:
            genero_obj, _ = Genero.objects.get_or_create(nome=valor)
            obra.genero = str(genero_obj.id)
        obra.save(update_fields=['genero'])


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_obra_metadata_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(
            convert_genero_text_to_fk,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='obra',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='obras.genero'),
        ),
    ]
