# Generated by Django 6.0.1 on 2026-03-08 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0004_genero_alter_obra_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='extensao',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensoes', to='obras.nota'),
        ),
        migrations.CreateModel(
            name='Tonalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tonalidades', to='obras.modo')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tonalidades', to='obras.nota')),
            ],
        ),
        migrations.AlterField(
            model_name='obra',
            name='tonalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='obras.tonalidade'),
        ),
    ]
