# Generated by Django 6.0.1 on 2026-03-08 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0005_modo_alter_extensao_nota_tonalidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='compositor',
            name='apelido',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registacao',
            name='geral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registacoes_geral', to='obras.registo'),
        ),
        migrations.AlterField(
            model_name='registacao',
            name='mao_direita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registacoes_direita', to='obras.registo'),
        ),
        migrations.AlterField(
            model_name='registacao',
            name='mao_esquerda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registacoes_esquerda', to='obras.registo'),
        ),
    ]
