# Generated by Django 6.0.1 on 2026-03-08 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0006_registo_compositor_apelido_alter_registacao_geral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonalidade',
            name='modo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tonalidades', to='obras.modo'),
        ),
    ]
