# Generated by Django 6.0.1 on 2026-03-08 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0007_alter_tonalidade_modo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='tonalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='obras.tonalidade'),
        ),
    ]
