# Generated by Django 6.0.1 on 2026-03-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0008_alter_obra_tonalidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensao',
            name='simples',
        ),
        migrations.AddField(
            model_name='extensao',
            name='tipo',
            field=models.CharField(default='', max_length=2),
        ),
    ]
