# Generated by Django 6.0.1 on 2026-03-08

import django.db.models.deletion
from django.db import migrations, models


def clear_registacoes_before_fk_change(apps, schema_editor):
    Registacao = apps.get_model("obras", "Registacao")
    Registacao.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0009_remove_extensao_simples_extensao_tipo"),
    ]

    operations = [
        migrations.RunPython(clear_registacoes_before_fk_change, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="registacao",
            name="orgao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registacoes",
                to="obras.orgao",
            ),
        ),
    ]
