# Generated by Django 6.0.1 on 2026-03-08 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0010_alter_registacao_orgao_to_orgao_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgao',
            name='extensao_fim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgaos_fim', to='obras.extensao'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='extensao_inicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgaos_inicio', to='obras.extensao'),
        ),
    ]
