# Generated by Django 6.0.1 on 2026-03-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0011_alter_orgao_extensao_fim_alter_orgao_extensao_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgao',
            options={'ordering': ['ordem']},
        ),
        migrations.AlterModelOptions(
            name='registacao',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='orgao',
            name='ordem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registacao',
            name='ordem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
