# Generated by Django 6.0.1 on 2026-03-09 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0012_alter_orgao_options_alter_registacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registacao',
            name='geral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registacoes_geral', to='obras.registo'),
        ),
        migrations.AlterField(
            model_name='registacao',
            name='mao_direita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registacoes_direita', to='obras.registo'),
        ),
        migrations.AlterField(
            model_name='registacao',
            name='mao_esquerda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registacoes_esquerda', to='obras.registo'),
        ),
    ]
