# Generated by Django 6.0.3 on 2026-04-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0013_alter_registacao_geral_alter_registacao_mao_direita_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="extensao",
            constraint=models.UniqueConstraint(
                fields=("nota", "oitava", "tipo"), name="unique_extensao"
            ),
        ),
    ]
