# Generated by Django 6.0.3 on 2026-04-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0014_extensao_unique_extensao"),
    ]

    operations = [
        migrations.AddField(
            model_name="obra",
            name="codigo",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
