# Generated by Django 6.0.3 on 2026-04-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0015_obra_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="obra",
            name="obm",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="obra",
            name="observacoes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
