# Generated by Django 6.0.3 on 2026-04-30 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0016_obra_obm_obra_observacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="compositor",
            name="a",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="compositor",
            name="d",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="compositor",
            name="fl",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="compositor",
            name="morte",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="compositor",
            name="morte_c",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="compositor",
            name="nascimento",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="compositor",
            name="nascimento_c",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name="Referencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                ("url", models.URLField(blank=True)),
                (
                    "compositor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referencias",
                        to="obras.compositor",
                    ),
                ),
            ],
        ),
    ]
