# Generated by Django 6.0.4 on 2026-05-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0017_compositor_a_compositor_d_compositor_fl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="obra",
            name="from_catalogo",
            field=models.TextField(blank=True, default=""),
        ),
    ]
