# Generated by Django 6.0.4 on 2026-05-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0018_obra_from_catalogo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="obra",
            old_name="from_catalogo",
            new_name="info_catalogo",
        ),
    ]
